---
__chrony_service_name: chronyd
__chrony_config_location: /etc/chrony.conf
__chrony_config_keyfile: /etc/chrony.keys
__chrony_config_driftfile: /var/lib/chrony/drift

__ntpd_service_name: ntpd
__openntpd_service_name: openntpd
__timesyncd_service_name: systemd-timesyncd
