---
# ------------------------------------------------------------------------------
# Installation
# ------------------------------------------------------------------------------

# enables/disables management of repositories
docker_manage_repository: true

# RPM repository URL to be used for installation on CentOS systems
docker_centos_repo_url: "https://download.docker.com/linux/centos/$releasever/$basearch/stable"

# RPM repository URL to be used for installation on RHEL systems
docker_rhel_repo_url: "https://download.docker.com/linux/rhel/$releasever/$basearch/stable"

# APT repository URL to be used for installation
docker_debian_repo_url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}"

# whether or not to install Docker Python library
docker_install_python_docker: true


# ------------------------------------------------------------------------------
# Service
# ------------------------------------------------------------------------------

# service enabled on boot
docker_service_enabled: true

# service run state (started, stopped, restarted)
docker_service_state: started

# restart service on configuration change
docker_service_restart_on_change: true



# ------------------------------------------------------------------------------
# Configuration
# ------------------------------------------------------------------------------

# configuration of the Docker daemon (key-value pairs)
# https://docs.docker.com/engine/reference/commandline/dockerd/#daemon-configuration-file
docker_config: {}

# list of users to be added to the Docker group (allow users to control Docker)
docker_users: []
