---
- name: include OS-specific variables
  tags: [postfix, always]
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_os_family | lower }}_{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_os_family | lower }}.yml"
        - "{{ ansible_distribution | lower }}_{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_distribution | lower }}.yml"
      skip: true

- name: include installation tasks
  tags: [postfix, postfix_install, install]
  ansible.builtin.include_tasks: "{{ item  }}"
  with_first_found:
    - "install_{{ ansible_os_family | lower }}_{{ ansible_distribution_major_version }}.yml"
    - "install_{{ ansible_os_family | lower }}.yml"
    - "install_{{ ansible_distribution | lower }}_{{ ansible_distribution_major_version }}.yml"
    - "install_{{ ansible_distribution | lower }}.yml"

- name: include certificate copy tasks
  ansible.builtin.import_tasks: copy_certificates.yml
  tags: [postfix, postfix-certs, certs]

- name: include dummy certificate creation tasks
  ansible.builtin.include_tasks: create_dummy_certificate.yml
  tags: [postfix, postfix-certs, certs]
  when: postfix_create_dummy_certificate | bool

- name: include configuration tasks
  ansible.builtin.import_tasks: configure.yml
  tags: [postfix, postfix_config, config]

- name: flush handlers
  ansible.builtin.meta: flush_handlers

- name: include service tasks
  ansible.builtin.import_tasks: service.yml
  tags: [postfix, postfix_service, service]
