---
- name: restart chrony
  ansible.builtin.service:
    name: "{{ __chrony_service_name }}"
    state: restarted
  when:
    - chrony_service_restart_on_change | bool
    - chrony_service_state != 'stopped'
