---
# ------------------------------------------------------------------------------
# Server
# ------------------------------------------------------------------------------

- when: nfs_role in ['server', 'all']
  block:
    - name: manage nfs server services
      ansible.builtin.service:
        name: "{{ __nfs_server_service }}"
        state: "{{ nfs_service_state }}"
        enabled: "{{ nfs_service_enabled }}"



# ------------------------------------------------------------------------------
# Client
# ------------------------------------------------------------------------------

- when: nfs_role in ['client', 'all']
  block:
    - name: manage nfs client services
      ansible.builtin.service:
        name: "{{ __nfs_client_service }}"
        state: "{{ nfs_service_state }}"
        enabled: "{{ nfs_service_enabled }}"
