---
# https://man7.org/linux/man-pages/man5/nfs.conf.5.html
__nfs_config_defaults:
  general: {}
  exportfs: {}
  gssd:
    "use-gss-proxy": true
  lockd: {}
  mountd: {}
  nfsdcltrack: {}
  # https://man7.org/linux/man-pages/man8/rpc.nfsd.8.html
  nfsd:
    port: 2049

    # number of threads to start
    threads: 8

    # use tcp only
    udp: false
    tcp: true

    # disable old versions of NFS
    vers2: false
    vers3: false

  statd: {}
  "sm-notify": {}



# https://man7.org/linux/man-pages/man5/nfsmount.conf.5.html
__nfs_mount_config_defaults:
  mount_points: {}
  servers: {}
  global:
    # The NFS protocol version number used to contact the server's NFS service.
    # If the server does not support the requested version, the mount request
    # fails
    nfsvers: 4
    # How to handle times out from servers
    hard: True
    # The amount of time, in tenths of a seconds, the client
    # will wait for a response from the server before retransmitting
    # the request.
    timeo: 300
    # Server Port
    port: 2049
    # RPCGSS security flavors
    sec: sys:krb5:krb5i:krb5p
    # Turn of the caching of that access time
    noatime: true



# https://linux.die.net/man/5/idmapd.conf
__nfs_idmapd_config_defaults:
  general:
    Verbosity: 0
  mapping:
    Nobody-User: nobody
    Nobody-Group: nobody
  translation: {}
  static: {}
  umich_schema: {}

__nfs_idmapd_config_sssd:
  translation:
    Method: sss



# https://www.systutorials.com/docs/linux/man/7-nfs.systemd/
__nfs_server_service: nfs-server
__nfs_client_service: nfs-client.target
