---
- when: cfg.state | default('present') == 'present'
  block:
    - name: ensure '{{ path | dirname }}' dir exists
      ansible.builtin.file:
        path: "{{ path | dirname }}"
        state: directory
        mode: 0755

    - name: create '{{ path }}' from content
      ansible.builtin.copy:
        content: "{{ cfg.content }}"
        dest: "{{ path }}"
        owner: "{{ cfg.owner | default(linux_profile_default_owner) | default(omit) }}"
        group: "{{ cfg.group | default(linux_profile_default_group) | default(omit) }}"
        mode: "{{ cfg.mode | default(linux_profile_default_mode) | default(omit) }}"
      when:
        - cfg.content is defined

    - name: create '{{ path }}' from file
      ansible.builtin.copy:
        src: "{{ cfg.file }}"
        dest: "{{ path }}"
        owner: "{{ cfg.owner | default(linux_profile_default_owner) | default(omit) }}"
        group: "{{ cfg.group | default(linux_profile_default_group) | default(omit) }}"
        mode: "{{ cfg.mode | default(linux_profile_default_mode) | default(omit) }}"
      when:
        - cfg.content is not defined
        - cfg.file is defined

    - name: create '{{ path }}' from template
      ansible.builtin.template:
        src: "{{ cfg.template }}"
        dest: "{{ path }}"
        owner: "{{ cfg.owner | default(linux_profile_default_owner) | default(omit) }}"
        group: "{{ cfg.group | default(linux_profile_default_group) | default(omit) }}"
        mode: "{{ cfg.mode | default(linux_profile_default_mode) | default(omit) }}"
        lstrip_blocks: true
      when:
        - cfg.content is not defined
        - cfg.file is not defined
        - cfg.template is defined

- name: remove '{{ path }}'
  ansible.builtin.file:
    path: "{{ path }}"
    state: absent
  when: cfg.state | default('present') == 'absent'
