---
- name: disable other NTP services
  ansible.builtin.include_tasks: disable_other_ntp_services.yml
  when: chrony_service_enabled or chrony_service_state != 'stopped'

- name: configure Chrony
  ansible.builtin.template:
    src: chrony.conf.j2
    dest: "{{ __chrony_config_location }}"
    owner: root
    group: root
    mode: 0644
    lstrip_blocks: true
    trim_blocks: true
  notify: restart chrony

- name: set timezone
  community.general.timezone:
    name: "{{ chrony_timezone }}"
  when: chrony_timezone is not none
  notify: restart chrony

- name: flush handlers to apply Chrony settings
  ansible.builtin.meta: flush_handlers
